Update build-docker.yml

diff --git a/.github/workflows/build-docker.yml b/.github/workflows/build-docker.yml
--- a/.github/workflows/build-docker.yml
+++ b/.github/workflows/build-docker.yml
@@ -1,6 +1,8 @@
 name: Build Docker
 
 on:
+  schedule:
+    - cron: "0 0 * * *"
   repository_dispatch:
   workflow_dispatch:
     inputs:
@@ -40,6 +42,14 @@ jobs:
     if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}
 
     steps:
+      - name: Clear workspace
+        working-directory: ${{ github.workspace }}
+        run: |
+          echo -e "Current working directory: $(pwd)"
+          rm -rf ${{ github.workspace }}/*
+          df -hT ${PWD}
+          echo "status=success" >> ${GITHUB_OUTPUT}
+
       # - name: Install cosign
       #   if: github.event_name != 'pull_request'
       #   uses: sigstore/cosign-installer@main
@@ -101,68 +111,6 @@ jobs:
           # ========== END ==========
           echo "status=success" >> ${GITHUB_OUTPUT}
 
-      # - name: Clear environment
-      #   id: clearinit
-      #   env:
-      #     DEBIAN_FRONTEND: noninteractive
-      #   working-directory: /
-      #   run: |
-      #     echo -e "Current working directory: $(pwd)"
-      #     # 删除docker所有镜像
-      #     docker rmi $(docker images -q) 2>/dev/null
-      #     # 如果环境变量 AGENT_TOOLSDIRECTORY 不为空，则删除该目录及其所有内容
-      #     [[ -n "${AGENT_TOOLSDIRECTORY}" ]] && sudo rm -rf "${AGENT_TOOLSDIRECTORY}"
-      #     # 删除指定的目录及其所有内容，忽略所有错误信息
-      #     sudo rm -rf /usr/share/dotnet /etc/apt/sources.list.d /usr/local/lib/android 2>/dev/null
-      #     # 关闭所有交换空间 删除指定的交换文件
-      #     sudo swapoff -a
-      #     sudo rm -f /swapfile /mnt/swapfile
-      #     df -Th
-      #     echo "status=success" >> ${GITHUB_OUTPUT}
-
-      # - name: Create simulated physical disk
-      #   id: disk
-      #   working-directory: /
-      #   if: ${{ steps.init.outputs.status }} == 'success' && !cancelled()
-      #   run: |
-      #     echo -e "Current working directory: $(pwd)"
-      #     # 计算 /mnt 分区的可用空间（减去 1GB 作为缓冲）, 计算根分区的可用空间（减去 4GB 作为缓冲）
-      #     mnt_size=$(expr $(df -h /mnt | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 1)
-      #     root_size=$(expr $(df -h / | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 4)
-      #     # 创建一个大小为 mnt_size 的文件 /mnt/mnt.img, 创建一个大小为 root_size 的文件 /root.img
-      #     sudo truncate -s "${mnt_size}"G /mnt/mnt.img
-      #     sudo truncate -s "${root_size}"G /root.img
-      #     # 将这两个文件关联到 loop 设备, 在这两个 loop 设备上创建物理卷, 创建一个名为 github 的卷组，包含这两个物理卷
-      #     sudo losetup /dev/loop6 /mnt/mnt.img
-      #     sudo losetup /dev/loop7 /root.img
-      #     sudo pvcreate /dev/loop6
-      #     sudo pvcreate /dev/loop7
-      #     sudo vgcreate github /dev/loop6 /dev/loop7
-
-      #     # 在 github 卷组上创建一个名为 runner 的逻辑卷，使用所有可用空间, 在 runner 逻辑卷上创建一个 XFS 文件系统
-      #     sudo lvcreate -n runner -l 100%FREE github
-      #     sudo mkfs.xfs /dev/github/runner
-      #     # 创建一个挂载点 ${path_build}, 将 runner 逻辑卷挂载到 ${path_build}, 将 ${path_build} 的所有者和组更改为 runner
-      #     sudo mkdir -p ${path_build}
-      #     sudo mount /dev/github/runner ${path_build}
-      #     sudo chown -R runner.runner ${path_build}
-
-      #     df -Th
-      #     echo "status=success" >> ${GITHUB_OUTPUT}
-
-      # - name: Setup workspace
-      #   id: workspace
-      #   working-directory: /
-      #   # if: ${{ steps.disk.outputs.status }} == 'success' && !cancelled()
-      #   run: |
-      #     echo -e "Current working directory: $(pwd)"
-
-      #     # 创建基本工作目录 path_workspace
-      #     mkdir -p ${path_workspace}
-
-      #     df -hT ${PWD}
-      #     echo "status=success" >> ${GITHUB_OUTPUT}
-
       - name: Checkout DIY
         uses: actions/checkout@main
         with:
@@ -171,19 +119,6 @@ jobs:
           fetch-depth: 1
           # Relative path under $GITHUB_WORKSPACE to place the repository
           path: ${{ github.event.repository.name }}
-
-      # - name: Clone DIY
-      #   id: clonediy
-      #   working-directory: ${{ env.path_workspace }}
-      #   # if: ${{ steps.disk.outputs.status }} == 'success' && !cancelled()
-      #   run: |
-      #     echo -e "Current working directory: $(pwd)"
-
-      #     git clone ${repo_diy} ${path_diy} --single-branch --depth=1 --branch=main
-      #     echo -e "repo_diy: [ ${repo_diy} ]\nBRANCH: [ main ]"
-
-      #     df -hT ${PWD}
-      #     echo "status=success" >> ${GITHUB_OUTPUT}
 
       - name: Set up QEMU
         uses: docker/setup-qemu-action@master
@@ -217,6 +152,47 @@ jobs:
       #       await exec.exec('dpkg-query -W -f="${Version}" cloudflare-warp', [], options);
       #       return version.trim();
 
+      # # Add cloudflare gpg key
+      # && OS_ARCH=$(dpkg --print-architecture) \
+      # && OS_VER=$(lsb_release -cs) \
+      # && curl -fsSL https://pkg.cloudflareclient.com/pubkey.gpg | gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg \
+      # && echo "deb [arch=${OS_ARCH} signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ ${OS_VER} main" > /etc/apt/sources.list.d/cloudflare-client.list \
+      # # Install cloudflare-warp
+      # && apt-get update \
+      # && apt-get install -y \
+      #     cloudflare-warp \
+
+      - name: Get package version
+        id: version
+        working-directory: ${{ github.workspace }}
+        run: |
+          echo -e "Current working directory: $(pwd)"
+
+          # APT
+          sudo -E apt-get -y -qq update
+          sudo -E apt-get -y -qq install \
+          curl \
+          gpg \
+
+          # Add cloudflare gpg key
+          curl -fsSL https://pkg.cloudflareclient.com/pubkey.gpg | gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
+          sudo -E apt-get -y -qq update
+
+          # dpkg -l <package-name>:<architecture>
+          ver_amd64=$(dpkg-query -W -f='${Version}\n' cloudflare-warp:amd64)
+          ver_arm64=$(dpkg-query -W -f='${Version}\n' cloudflare-warp:arm64)
+
+          if [ "$ver_amd64" != "$ver_arm64" ]; then
+            echo "Error: Version mismatch between amd64 and arm64"
+            exit 1
+          else
+            echo "Version: $ver_amd64"
+            echo "::set-output name=version::$ver_amd64"
+          fi
+
+          echo "ver=${TAGS_NAME}" >> ${GITHUB_OUTPUT}
+          echo "status=success" >> ${GITHUB_OUTPUT}
+
       - name: Extract metadata (tags, labels) for Docker
         id: meta
         uses: docker/metadata-action@master
@@ -240,11 +216,10 @@ jobs:
           # build-args: |
           #
 
-      # - name: Clear workspace
-      #   id: clearwork
-      #   working-directory: ${{ env.path_build }}
-      #   run: |
-      #     echo -e "Current working directory: $(pwd)"
-      #     rm -rf ./* 2>/dev/null
-      #     df -hT ${PWD}
-      #     echo "status=success" >> ${GITHUB_OUTPUT}
+      - name: Clear workspace
+        working-directory: ${{ github.workspace }}
+        run: |
+          echo -e "Current working directory: $(pwd)"
+          rm -rf ${{ github.workspace }}/*
+          df -hT ${PWD}
+          echo "status=success" >> ${GITHUB_OUTPUT}
